
[[docs]]
  name = "Overview"
  weight = 1
  identifier = "overview"
  url = "/docs/overview/"


[[docs]]
  name = "Data Zoo"
  weight = 1000
  identifier = "datazoo"
  url = "/docs/data-zoo/"

[[docs]]
  name = "Storage Engines"
  weight = 2000
  identifier = "storage"
  url = "/docs/storage/"

[[docs]]
  name = "Runtime Environment"
  weight = 3000
  identifier = "runtime"
  url = "/docs/runtime/"

[[docs]]
  name = "Linked Data & SDN"
  weight = 4000
  identifier = "linked-data"
  url = "/docs/linked-data/"


[[docs]]
  name = "Digital Philosophy"
  weight = 5000
  identifier = "d-phil"
  url = "/docs/d-phil/"

[[docs]]
  name = "Memoria Build Tool"
  weight = 6000
  identifier = "mbt"
  url = "/docs/mbt/"


[[docs]]
  name = "Testing Framework"
  weight = 7000
  identifier = "tests"
  url = "/docs/tests/"

[[docs]]
  name = "Datascope"
  weight = 8000
  identifier = "datascope"
  url = "/docs/datascope/"

[[docs]]
  name = "Misc"
  weight = 9000
  identifier = "misc"
  url = "/docs/misc/"


[[main]]
  name = "Docs"
  url = "/docs/overview/introduction/"
  weight = 10

[[main]]
  name = "Tutorial"
  weight = 20
  url = "/tutorial/quick-start"

[[main]]
  name = "API"
  weight = 30
  url = "/api/overview/"

[[main]]
  name = "Python"
  weight = 40
  url = "/python/overview/"

[[main]]
  name = "Subprojects"
  weight = 50
  url = "/subprojects/overview/"


[[main]]
  name = "Issues"
  url = "https://github.com/victor-smirnov/memoria/issues"
  weight = 60


[[main]]
  name = "Discussions"
  url = "https://github.com/victor-smirnov/memoria/discussions"
  weight = 70

[[main]]
  name = "Releases"
  url = "https://github.com/victor-smirnov/memoria/wiki"
  weight = 80



[[social]]
  name = "GitHub"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-github\"><path d=\"M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22\"></path></svg>"
  url = "https://github.com/victor-smirnov/memoria"
  post = "v0.1.0"
  weight = 10

#[[social]]
#  name = "Twitter"
#  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-twitter\"><path d=\"M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z\"></path></svg>"
#  url = "https://twitter.com/victor-smirnov"
#  weight = 20

[[footer]]
  name = "Privacy"
  url = "/privacy-policy/"
  weight = 10

[[tutorial]]
  name = "Tutorial"
  weight = 10
  identifier = "tutorial"
  url = "/tutorial/"

[[api]]
  name = "API"
  weight = 10
  identifier = "api"
  url = "/api/"

[[python]]
  name = "Python"
  identifier = "python"
  weight = 10
  url = "/python/"

[[subprojects]]
  name = "Subprojects"
  identifier = "subprojects"
  weight = 10
  url = "/subprojects/"
